### ISSUE TITLE
Another overview for you

### ISSUE THREAD

**Issue by pfeerick** [zerotoney/ZeroPowerV3#1]
Was bored, so took a picture of my board and annotated it... Free to use as you wish... excalidraw file attached for the diagram. I guess I could do a PR adding a readme to the repo if you want it as a front page quick reference? 

I'll do the Batman and Iron Man PCBs as well, either tomorrow or Sunday, as someone was asking about the pinout for those... 

[Zero Multi-Power Supply V3.0.excalidraw.zip](https://github.com/user-attachments/files/16815100/Zero.Multi-Power.Supply.V3.0.excalidraw.zip)
![Zero Multi-Power Supply V3 0](https://github.com/user-attachments/assets/deacd363-a497-4142-a67d-f628b6034941)

**Comment by zerotoney** [comment]
Hi, pfeerick

Thank you so much for your help. It is very nice drawing. I will put it into the description. 

Regards

Toney

**Comment by pfeerick** [comment]
Hey, no problem... thanks for the great boards ;) 

edit: lol... I see you uploaded pinouts for those PCB also ... all good :) Can you add a note for the maximum voltage for those, as I don't think it was mentioned anywhere. 

Here's the batman and iron man PCBs... not quite so pretty but gets the job done. 
[batman and ironman PCBs.zip](https://github.com/user-attachments/files/16827424/batman.and.ironman.PCBs.zip)

![batman and ironman PCBs](https://github.com/user-attachments/assets/17f8fdfd-6913-47de-a6e0-ad738c4df306)
